---
# NOTE(mnasiadka): external_ids:system-id uniquely identifies a physical system, used by OVN and other controllers
- name: Set system-id
  become: true
  command: docker exec openvswitch_vswitchd ovs-vsctl set Open_vSwitch . external_ids:system-id={{ openvswitch_system_id }}

- name: Copy scripts to manage the extra OVS internal interfaces
  become: true
  template:
    src: extra_ovs_config.sh.j2
    dest: ensure_{{ item.interface_name }}_configured.sh
    mode: 0755
  when:
    - inventory_hostname in groups["network"]
      or (inventory_hostname in groups["compute"] and computes_need_external_bridge | bool )
  with_items: "{{ neutron_internal_ports }}"

- name: Run scripts to setup the extra OVS internal interfaces 
  become: true
  shell: |
    ./ensure_{{ item.interface_name }}_configured.sh
  args:
    executable: /bin/bash
  when:
    - inventory_hostname in groups["network"]
      or (inventory_hostname in groups["compute"] and computes_need_external_bridge | bool )
  with_items: "{{ neutron_internal_ports }}"

- name: Ensuring OVS bridge is properly setup
  become: true
  command: docker exec openvswitch_db /usr/local/bin/kolla_ensure_openvswitch_configured {{ item.0 }} {{ item.1 }}
  register: status
  changed_when: status.stdout.find('changed') != -1
  when:
    - inventory_hostname in groups["network"]
      or (inventory_hostname in groups["compute"] and computes_need_external_bridge | bool )
  with_together:
    - "{{ neutron_bridge_name.split(',') }}"
    - "{{ neutron_external_interface.split(',') }}"
